version: '2.3'

services:

  postgres:
    extends:
      file: services.yml
      service: postgres
    ports:
      - 5432:5432

  keycloak:
    extends:
      file: services.yml
      service: keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_IMPORT: /mnt/engineering-realm.json
    volumes:
      - ./keycloak/:/mnt/:ro
    depends_on:
      - postgres

networks:
  engineering:
